### PR TITLE
Exim Python integration

### PR DESCRIPTION
**Pull request by philpennock**
This is a tracking PR for code-review purposes, so that I can look over Todd's work with GitHub's tools, since I've gotten sucked into that workflow.  All this code is by @mrballcb and I haven't looked at it yet.

Pushed branch with:
```sh
git push github +refs/remotes/tlyons/master_volatile_python:refs/heads/tylons_python
```

### CODE REVIEW

**Comment by philpennock** [comment]
This is a stale PR, almost two years old, so there have been many changes.

The core of the work was good, the WIP Python3 looked good.

**Comment by tonyandrewmeyer** [comment]
What's the plan for this?  Is it likely that it would go in as an experimental feature at some point?  Is there some other PR where this is being done instead?  I can have people (who are familiar with embedding Python, but only slightly familiar with the Exim source) do some reviewing if that would help.

**Comment by philpennock** [comment]
Exim is a volunteer project with nothing along the lines of "project management"; plans are "what volunteers want to work on".  My closing the PR says "hey, this is way out of date".  @mrballcb now has a notification email somewhere, so he can decide if there's anything he wants to do, perhaps including taking you up on your offer.

I think the key is that the last commit in Todd's git.exim.org git repo for this work is from Sep 2013 and labelled "WIP", so he didn't then think it ready for merge.  I'll be happy to see this work go in, and to help review it when the time comes if that's desired, but don't have the time/capacity to take on the coding and test-suite integration myself.

(Honestly, we're not even big users of code-review within this project, since we don't have the people and time to do a good job of it; we do have a strong test suite, which we do insist upon before something can leave `EXPERIMENTAL_foo` status).

**Comment by tonyandrewmeyer** [comment]
Cool.  My discussion with Todd about this is still sitting in the to-do list since way back in 2013 also.  I'd love to see it get in, but it obviously hasn't been high enough priority for us to do anything with it in the last couple of years either.

I'll talk about it with Todd figure out if we should pick it up (updating the code, tests, submitting a new PR) or if he's still keen or what.

Thanks!

**Pull request closed without merging**
